export const ACTIONS = {
    TODO_ADD: 'Add',
    TODO_TOGGLE: 'TODO_TOGGLE',
    DELETE: 'delete',
    FETCH_INIT: 'FETCH_INIT',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_ERROR: 'FETCH_ERROR',
    FETCH_JAR_SUCCESS: 'FETCH_JAR_SUCCESS',
}